-- Create speeches table
CREATE TABLE IF NOT EXISTS speeches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mp_id INT REFERENCES mps(id),
    sitting INT,
    date DATE,
    speaker_name TEXT,
    content TEXT,
    topic TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(mp_id, sitting, date, content) -- Prevent duplicates (naive check)
);

-- Enable RLS
ALTER TABLE speeches ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access" ON speeches FOR SELECT USING (true);

-- Create policy for service role write access
CREATE POLICY "Allow service role write access" ON speeches FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role update access" ON speeches FOR UPDATE USING (true);
