-- Create consistency_reports table
CREATE TABLE IF NOT EXISTS consistency_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mp_id INT REFERENCES mps(id),
    topic TEXT NOT NULL,
    speech_quote TEXT,
    vote_result TEXT,
    verdict TEXT CHECK (verdict IN ('Spójny', 'Niespójny', 'Niejednoznaczny')),
    analysis TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(mp_id, topic)
);

-- Enable RLS
ALTER TABLE consistency_reports ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access" ON consistency_reports FOR SELECT USING (true);

-- Create policy for service role write access
CREATE POLICY "Allow service role write access" ON consistency_reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role update access" ON consistency_reports FOR UPDATE USING (true);
