-- Create asset_declarations table
CREATE TABLE IF NOT EXISTS asset_declarations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mp_id INT REFERENCES mps(id),
    pdf_url TEXT NOT NULL,
    year TEXT,
    parsed_content JSONB,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(mp_id, pdf_url)
);

-- Enable RLS
ALTER TABLE asset_declarations ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access" ON asset_declarations FOR SELECT USING (true);

-- Create policy for service role write access
CREATE POLICY "Allow service role write access" ON asset_declarations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role update access" ON asset_declarations FOR UPDATE USING (true);
