-- Europarlament Votes Tables

-- 1. Table for Vote Metadata
create table if not exists euro_votes (
  id text primary key, -- The weird ID e.g. MTG-PL-2024-01-15-DEC-163200
  title text not null,
  description text, -- e.g. "Request by ECR Group"
  date timestamptz not null,
  
  -- Aggregated Counts
  votes_for int default 0,
  votes_against int default 0,
  votes_abstain int default 0,
  
  created_at timestamptz default now()
);

-- 2. Table for Individual MEP Results
create table if not exists euro_vote_results (
  id bigint generated by default as identity primary key,
  vote_id text references euro_votes(id) on delete cascade not null,
  mep_id int references euro_meps(api_id) on delete cascade not null, -- Links to api_id in euro_meps
  vote text not null check (vote in ('For', 'Against', 'Abstain', 'Absent')),
  
  created_at timestamptz default now()
);

-- Indexes
create index if not exists idx_euro_votes_date on euro_votes(date desc);
create index if not exists idx_euro_vote_results_vote_id on euro_vote_results(vote_id);
create index if not exists idx_euro_vote_results_mep_id on euro_vote_results(mep_id);

-- RLS
alter table euro_votes enable row level security;
alter table euro_vote_results enable row level security;

create policy "Public Read Euro Votes"
  on euro_votes for select
  using (true);
  
create policy "Public Read Euro Vote Results"
  on euro_vote_results for select
  using (true);

create policy "Service Role Full Access Euro Votes"
  on euro_votes for all
  using ( auth.role() = 'service_role' );

create policy "Service Role Full Access Euro Vote Results"
  on euro_vote_results for all
  using ( auth.role() = 'service_role' );
