events {}

http {
    upstream backend {
        server backend:8000;
    }

    upstream n8n {
        server n8n:5678;
    }

    server {
        listen 80;
        server_name api.otwartyparlament.pl n8n.otwartyparlament.pl;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Tutaj w przyszłości dodamy bloki SSL (po wygenerowaniu certyfikatów)
    # Na start wystarczy HTTP do testów lub self-signed, ale Certbot wymaga HTTP na start.
}
