server {
    listen 80;
    server_name otwartyparlament.pl api.otwartyparlament.pl n8n.otwartyparlament.pl;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
