"""Initial migration

Revision ID: 0d53165a6f8c
Revises: 
Create Date: 2026-02-10 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0d53165a6f8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # 1. Base tables with no FKs or internal dependencies
    op.create_table('mps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('club', sa.String(), nullable=True),
        sa.Column('district', sa.String(), nullable=True),
        sa.Column('photo_url', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('stats_attendance', sa.Float(), nullable=True),
        sa.Column('stats_rebellion', sa.Integer(), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.Column('api_id', sa.Integer(), nullable=True),
        sa.Column('seat_number', sa.Integer(), nullable=True),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('birth_location', sa.String(), nullable=True),
        sa.Column('profession', sa.String(), nullable=True),
        sa.Column('education_level', sa.String(), nullable=True),
        sa.Column('education_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('biography', sa.Text(), nullable=True),
        sa.Column('link_sejm', sa.String(), nullable=True),
        sa.Column('stats_bills_count', sa.Integer(), nullable=True),
        sa.Column('stats_speeches_count', sa.Integer(), nullable=True),
        sa.Column('stats_interpellations_count', sa.Integer(), nullable=True),
        sa.Column('stats_activity_score', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mps_club'), 'mps', ['club'], unique=False)
    op.create_index(op.f('ix_mps_first_name'), 'mps', ['first_name'], unique=False)
    op.create_index(op.f('ix_mps_id'), 'mps', ['id'], unique=False)
    op.create_index(op.f('ix_mps_last_name'), 'mps', ['last_name'], unique=False)
    op.create_index(op.f('ix_mps_slug'), 'mps', ['slug'], unique=False)
    op.create_index(op.f('ix_mps_term'), 'mps', ['term'], unique=False)

    op.create_table('committees',
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('name_genitive', sa.String(), nullable=True),
        sa.Column('committee_type', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('code')
    )

    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('name_pl', sa.String(), nullable=True),
        sa.Column('icon', sa.String(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)

    op.create_table('interpellations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('sent_date', sa.Date(), nullable=True),
        sa.Column('last_modified', sa.DateTime(), nullable=True),
        sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('reply_content', sa.Text(), nullable=True),
        sa.Column('ai_summary', sa.Text(), nullable=True),
        sa.Column('expert_summary', sa.Text(), nullable=True),
        sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('importance', sa.Integer(), nullable=True),
        sa.Column('street_title', sa.String(), nullable=True),
        sa.Column('meta_description', sa.String(), nullable=True),
        sa.Column('seo_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('personas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('vector_embedding', Vector(768), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interpellations_id'), 'interpellations', ['id'], unique=False)

    # 2. Tables dependent on mps
    op.create_table('bills',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('process_id', sa.String(), nullable=True),
        sa.Column('number', sa.String(), nullable=True),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('mp_id', sa.Integer(), nullable=True),
        sa.Column('topic', sa.String(), nullable=True),
        sa.Column('importance', sa.Integer(), nullable=True),
        sa.Column('vector_embedding', Vector(768), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_number'), 'bills', ['number'], unique=False)
    op.create_index(op.f('ix_bills_process_id'), 'bills', ['process_id'], unique=False)
    op.create_index(op.f('ix_bills_term'), 'bills', ['term'], unique=False)
    op.create_index(op.f('ix_bills_topic'), 'bills', ['topic'], unique=False)
    op.create_index(op.f('ix_bills_type'), 'bills', ['type'], unique=False)

    op.create_table('asset_declarations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mp_id', sa.Integer(), nullable=True),
        sa.Column('year', sa.String(), nullable=True),
        sa.Column('pdf_url', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=True),
        sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_declarations_id'), 'asset_declarations', ['id'], unique=False)

    op.create_table('committee_members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('committee_code', sa.String(), nullable=True),
        sa.Column('mp_id', sa.Integer(), nullable=True),
        sa.Column('function', sa.String(), nullable=True),
        sa.Column('from_date', sa.Date(), nullable=True),
        sa.Column('to_date', sa.Date(), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['committee_code'], ['committees.code'], ),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_members_id'), 'committee_members', ['id'], unique=False)

    op.create_table('mp_relations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mp_id_a', sa.Integer(), nullable=True),
        sa.Column('mp_id_b', sa.Integer(), nullable=True),
        sa.Column('similarity_score', sa.Float(), nullable=True),
        sa.Column('relation_type', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['mp_id_a'], ['mps.id'], ),
        sa.ForeignKeyConstraint(['mp_id_b'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_relations_id'), 'mp_relations', ['id'], unique=False)

    op.create_table('mp_stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mp_id', sa.Integer(), nullable=True),
        sa.Column('stat_key', sa.String(), nullable=True),
        sa.Column('stat_value', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_stats_id'), 'mp_stats', ['id'], unique=False)
    op.create_index(op.f('ix_mp_stats_stat_key'), 'mp_stats', ['stat_key'], unique=False)

    op.create_table('speeches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mp_id', sa.Integer(), nullable=True),
        sa.Column('sitting', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('speaker_name', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('topic', sa.String(), nullable=True),
        sa.Column('statement_num', sa.Integer(), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.Column('vector_embedding', Vector(768), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speeches_id'), 'speeches', ['id'], unique=False)

    # 3. Tables dependent on bills (Vote depends on Bill)
    op.create_table('bill_analyses',
        sa.Column('bill_id', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('summary_expert', sa.Text(), nullable=True),
        sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('impact', sa.Text(), nullable=True),
        sa.Column('personas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('importance', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
        sa.PrimaryKeyConstraint('bill_id')
    )

    op.create_table('votes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sitting', sa.Integer(), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.Column('voting_number', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('title_raw', sa.String(), nullable=True),
        sa.Column('title_clean', sa.String(), nullable=True),
        sa.Column('verdict', sa.String(), nullable=True),
        sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('topic', sa.String(), nullable=True),
        sa.Column('importance', sa.Integer(), nullable=True),
        sa.Column('ai_summary', sa.Text(), nullable=True),
        sa.Column('expert_summary', sa.Text(), nullable=True),
        sa.Column('kind', sa.String(), nullable=True),
        sa.Column('vector_embedding', Vector(768), nullable=True),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
        sa.Column('print_number', sa.String(), nullable=True),
        sa.Column('bill_id', sa.Integer(), nullable=True),
        sa.Column('street_title', sa.String(), nullable=True),
        sa.Column('meta_description', sa.String(), nullable=True),
        sa.Column('seo_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_procedural', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('parent_vote_id', sa.Integer(), nullable=True),
        sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('personas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
        sa.ForeignKeyConstraint(['parent_vote_id'], ['votes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_bill_id'), 'votes', ['bill_id'], unique=False)
    op.create_index(op.f('ix_votes_date'), 'votes', ['date'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_print_number'), 'votes', ['print_number'], unique=False)
    op.create_index(op.f('ix_votes_sitting'), 'votes', ['sitting'], unique=False)
    op.create_index(op.f('ix_votes_term'), 'votes', ['term'], unique=False)
    op.create_index(op.f('ix_votes_topic'), 'votes', ['topic'], unique=False)

    # 4. Tables dependent on votes
    op.create_table('vote_analyses',
        sa.Column('vote_id', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('summary_expert', sa.Text(), nullable=True),
        sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('analysis_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('mind_map', sa.Text(), nullable=True),
        sa.Column('procedural_context', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
        sa.PrimaryKeyConstraint('vote_id')
    )

    op.create_table('vote_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mp_id', sa.Integer(), nullable=True),
        sa.Column('vote_id', sa.Integer(), nullable=True),
        sa.Column('result', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_results_id'), 'vote_results', ['id'], unique=False)

    # 5. Remaining tables
    op.create_table('interpellation_authors',
        sa.Column('interpellation_id', sa.Integer(), nullable=False),
        sa.Column('mp_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['interpellation_id'], ['interpellations.id'], ),
        sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
        sa.PrimaryKeyConstraint('interpellation_id', 'mp_id')
    )

    op.create_table('committee_sittings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('committee_code', sa.String(), nullable=True),
        sa.Column('sitting_number', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('room', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('is_remote', sa.Boolean(), nullable=True),
        sa.Column('is_closed', sa.Boolean(), nullable=True),
        sa.Column('video_url', sa.String(), nullable=True),
        sa.Column('agenda', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('term', sa.Integer(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['committee_code'], ['committees.code'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_sittings_committee_code'), 'committee_sittings', ['committee_code'], unique=False)
    op.create_index(op.f('ix_committee_sittings_date'), 'committee_sittings', ['date'], unique=False)
    op.create_index(op.f('ix_committee_sittings_id'), 'committee_sittings', ['id'], unique=False)
    op.create_index(op.f('ix_committee_sittings_status'), 'committee_sittings', ['status'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committee_sittings')
    op.drop_table('interpellation_authors')
    op.drop_table('vote_results')
    op.drop_table('vote_analyses')
    op.drop_table('votes')
    op.drop_table('bill_analyses')
    op.drop_table('speeches')
    op.drop_table('mp_stats')
    op.drop_table('mp_relations')
    op.drop_table('committee_members')
    op.drop_table('asset_declarations')
    op.drop_table('bills')
    op.drop_table('interpellations')
    op.drop_table('categories')
    op.drop_table('committees')
    op.drop_table('mps')
    # ### end Alembic commands ###
