"""Add Topic model

Revision ID: ac0890168a9e
Revises: 0d53165a6f8c
Create Date: 2026-02-18 19:08:35.660222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac0890168a9e'
down_revision: Union[str, None] = '0d53165a6f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('related_vote_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_bill_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.drop_index(op.f('idx_processes_description_gin'), table_name='processes', postgresql_using='gin')
    op.drop_table('processes')
    op.drop_table('consistency_reports')
    op.drop_table('test_1_mistral')
    op.drop_table('podsumowania_4')
    op.drop_table('schema_migrations')
    op.drop_table('bill_insights')
    op.drop_index(op.f('idx_club_memberships_club'), table_name='club_memberships')
    op.drop_index(op.f('idx_club_memberships_club_term'), table_name='club_memberships', postgresql_where='(to_date IS NULL)')
    op.drop_index(op.f('idx_club_memberships_current'), table_name='club_memberships', postgresql_where='(to_date IS NULL)')
    op.drop_index(op.f('idx_club_memberships_dates'), table_name='club_memberships')
    op.drop_index(op.f('idx_club_memberships_mp'), table_name='club_memberships')
    op.drop_index(op.f('idx_club_memberships_unique_current'), table_name='club_memberships', postgresql_where='(to_date IS NULL)')
    op.drop_table('club_memberships')
    op.drop_index(op.f('idx_bill_authors_mp_id'), table_name='bill_authors')
    op.drop_table('bill_authors')
    op.drop_table('parties')
    op.drop_index(op.f('idx_vote_categories_category'), table_name='vote_categories')
    op.drop_index(op.f('idx_vote_categories_primary'), table_name='vote_categories', postgresql_where='(is_primary = true)')
    op.drop_index(op.f('idx_vote_categories_vote'), table_name='vote_categories')
    op.drop_table('vote_categories')
    op.drop_table('speech_tags')
    op.drop_table('speech_summaries')
    op.drop_table('topic_arguments')
    op.create_index(op.f('ix_analysis_requests_id'), 'analysis_requests', ['id'], unique=False)
    op.alter_column('asset_declarations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('asset_declarations', 'year',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('asset_declarations', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('asset_declarations', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('asset_declarations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('asset_declarations_mp_id_pdf_url_key'), 'asset_declarations', type_='unique')
    op.create_index(op.f('ix_asset_declarations_id'), 'asset_declarations', ['id'], unique=False)
    op.drop_index(op.f('idx_bills_number'), table_name='bills')
    op.drop_index(op.f('idx_bills_type'), table_name='bills')
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_number'), 'bills', ['number'], unique=False)
    op.create_index(op.f('ix_bills_process_id'), 'bills', ['process_id'], unique=True)
    op.create_index(op.f('ix_bills_term'), 'bills', ['term'], unique=False)
    op.create_index(op.f('ix_bills_topic'), 'bills', ['topic'], unique=False)
    op.create_index(op.f('ix_bills_type'), 'bills', ['type'], unique=False)
    op.drop_column('bills', 'ai_summary')
    op.drop_column('bills', 'vector_embedding_old')
    op.drop_column('bills', 'ai_tags')
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('categories', 'name_pl',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('categories', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('idx_categories_level'), table_name='categories')
    op.drop_index(op.f('idx_categories_parent'), table_name='categories')
    op.drop_index(op.f('idx_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'weight')
    op.drop_column('categories', 'name_citizen')
    op.drop_column('categories', 'parent_id')
    op.drop_column('categories', 'keywords')
    op.drop_column('categories', 'display_order')
    op.alter_column('committee_members', 'committee_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('committee_members', 'function',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('committee_members_committee_code_mp_id_from_date_key'), 'committee_members', type_='unique')
    op.drop_index(op.f('idx_committee_members_code'), table_name='committee_members')
    op.drop_index(op.f('idx_committee_members_mp'), table_name='committee_members')
    op.create_index(op.f('ix_committee_members_id'), 'committee_members', ['id'], unique=False)
    op.create_foreign_key(None, 'committee_members', 'committees', ['committee_code'], ['code'])
    op.alter_column('committee_sittings', 'committee_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('committee_sittings', 'sitting_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('committee_sittings', 'room',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('committee_sittings', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('committee_sittings', 'video_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('committee_sittings_committee_code_sitting_number_term_key'), 'committee_sittings', type_='unique')
    op.drop_index(op.f('idx_committee_sittings_code'), table_name='committee_sittings')
    op.drop_index(op.f('idx_committee_sittings_date'), table_name='committee_sittings')
    op.drop_index(op.f('idx_committee_sittings_status'), table_name='committee_sittings')
    op.create_index(op.f('ix_committee_sittings_committee_code'), 'committee_sittings', ['committee_code'], unique=False)
    op.create_index(op.f('ix_committee_sittings_date'), 'committee_sittings', ['date'], unique=False)
    op.create_index(op.f('ix_committee_sittings_id'), 'committee_sittings', ['id'], unique=False)
    op.create_index(op.f('ix_committee_sittings_status'), 'committee_sittings', ['status'], unique=False)
    op.drop_constraint(op.f('fk_committee_sittings_committee'), 'committee_sittings', type_='foreignkey')
    op.create_foreign_key(None, 'committee_sittings', 'committees', ['committee_code'], ['code'])
    op.alter_column('committees', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('committees', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('committees', 'name_genitive',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('committees', 'committee_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('committees', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('committees_code_key'), 'committees', type_='unique')
    op.drop_column('committees', 'id')
    op.alter_column('euro_meps', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('euro_meps', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('euro_meps', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Poland'::text"))
    op.alter_column('euro_meps', 'national_party',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'eu_group',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'term',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.create_index(op.f('ix_euro_meps_id'), 'euro_meps', ['id'], unique=False)
    op.drop_column('euro_meps', 'total_votes')
    op.drop_column('euro_meps', 'last_updated')
    op.alter_column('euro_vote_results', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('euro_vote_results', 'vote_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('euro_vote_results', 'mep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('euro_vote_results', 'vote',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_euro_vote_results_mep_id'), table_name='euro_vote_results')
    op.drop_index(op.f('idx_euro_vote_results_vote_id'), table_name='euro_vote_results')
    op.create_index(op.f('ix_euro_vote_results_id'), 'euro_vote_results', ['id'], unique=False)
    op.drop_constraint(op.f('euro_vote_results_vote_id_fkey'), 'euro_vote_results', type_='foreignkey')
    op.drop_constraint(op.f('euro_vote_results_mep_id_fkey'), 'euro_vote_results', type_='foreignkey')
    op.create_foreign_key(None, 'euro_vote_results', 'euro_votes', ['vote_id'], ['id'])
    op.create_foreign_key(None, 'euro_vote_results', 'euro_meps', ['mep_id'], ['id'])
    op.drop_column('euro_vote_results', 'created_at')
    op.alter_column('euro_votes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('euro_votes', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('euro_votes', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('euro_votes', 'term',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('euro_votes', 'topic_tag',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('euro_votes_vector_idx'), table_name='euro_votes', postgresql_ops={'vector_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_euro_votes_date'), table_name='euro_votes')
    op.drop_index(op.f('idx_euro_votes_importance'), table_name='euro_votes')
    op.drop_index(op.f('idx_euro_votes_is_key'), table_name='euro_votes')
    op.create_index(op.f('ix_euro_votes_id'), 'euro_votes', ['id'], unique=False)
    op.drop_column('euro_votes', 'created_at')
    op.drop_column('euro_votes', 'vector_embedding_old')
    op.drop_index(op.f('idx_interpellation_authors_mp_id'), table_name='interpellation_authors')
    op.drop_index(op.f('idx_interpellations_mp'), table_name='interpellation_authors')
    op.create_foreign_key(None, 'interpellation_authors', 'interpellations', ['interpellation_id'], ['id'])
    op.create_foreign_key(None, 'interpellation_authors', 'mps', ['mp_id'], ['id'])
    op.alter_column('interpellations', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('interpellations', 'last_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_interpellations_content_gin'), table_name='interpellations', postgresql_using='gin')
    op.drop_index(op.f('idx_interpellations_sent_date'), table_name='interpellations')
    op.create_index(op.f('ix_interpellations_id'), 'interpellations', ['id'], unique=False)
    op.drop_column('interpellations', 'term')
    op.drop_column('interpellations', 'summary_expert')
    op.drop_column('interpellations', 'content_tsv')
    op.drop_column('interpellations', 'link_sejm')
    op.alter_column('mps', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mps', 'club',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mps', 'district',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mps', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mps', 'term',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('mps', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mps', 'seat_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Physical seat number in the Sejm Plenary Hall (Digital Twin mapping)',
               existing_nullable=True)
    op.alter_column('mps', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment=None,
               existing_comment='URL-friendly identifier generated from name (e.g. adam-lubonski)',
               existing_nullable=True)
    op.alter_column('mps', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mps', 'link_sejm',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('mps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('mps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_index(op.f('idx_mps_activity_score'), table_name='mps')
    op.drop_index(op.f('idx_mps_api_id_term'), table_name='mps')
    op.drop_index(op.f('idx_mps_slug'), table_name='mps')
    op.drop_index(op.f('idx_mps_stats_attendance'), table_name='mps')
    op.drop_index(op.f('idx_mps_stats_rebellion'), table_name='mps')
    op.create_index(op.f('ix_mps_club'), 'mps', ['club'], unique=False)
    op.create_index(op.f('ix_mps_first_name'), 'mps', ['first_name'], unique=False)
    op.create_index(op.f('ix_mps_id'), 'mps', ['id'], unique=False)
    op.create_index(op.f('ix_mps_last_name'), 'mps', ['last_name'], unique=False)
    op.create_index(op.f('ix_mps_slug'), 'mps', ['slug'], unique=False)
    op.create_index(op.f('ix_mps_term'), 'mps', ['term'], unique=False)
    op.drop_column('mps', 'declarations')
    op.alter_column('query_embeddings', 'query',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_query_embeddings_query'), table_name='query_embeddings')
    op.drop_constraint(op.f('query_embeddings_query_key'), 'query_embeddings', type_='unique')
    op.create_index(op.f('ix_query_embeddings_query'), 'query_embeddings', ['query'], unique=True)
    op.alter_column('sejm_prints', 'number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sejm_prints', 'process_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_sejm_prints_number'), 'sejm_prints', ['number'], unique=False)
    op.alter_column('sitting_agendas', 'sitting_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sitting_agendas', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sitting_agendas', 'print_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sitting_agendas_date'), table_name='sitting_agendas')
    op.drop_index(op.f('idx_sitting_agendas_sitting'), table_name='sitting_agendas')
    op.drop_constraint(op.f('sitting_agendas_sitting_number_point_number_title_key'), 'sitting_agendas', type_='unique')
    op.create_index(op.f('ix_sitting_agendas_date'), 'sitting_agendas', ['date'], unique=False)
    op.create_index(op.f('ix_sitting_agendas_id'), 'sitting_agendas', ['id'], unique=False)
    op.create_index(op.f('ix_sitting_agendas_sitting_number'), 'sitting_agendas', ['sitting_number'], unique=False)
    op.drop_column('sitting_agendas', 'raw_data')
    op.alter_column('sitting_summaries', 'term',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sitting_summaries', 'sitting_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sitting_summaries', 'summary_md',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sitting_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sitting_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sitting_summaries_term_sitting'), table_name='sitting_summaries')
    op.drop_constraint(op.f('sitting_summaries_term_sitting_number_key'), 'sitting_summaries', type_='unique')
    op.create_index(op.f('ix_sitting_summaries_id'), 'sitting_summaries', ['id'], unique=False)
    op.create_unique_constraint(None, 'sitting_summaries', ['sitting_number'])
    op.alter_column('speeches', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('speeches', 'speaker_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speeches', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speeches', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.alter_column('speeches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_speeches_date'), table_name='speeches')
    op.drop_index(op.f('idx_speeches_mp_id_date'), table_name='speeches')
    op.drop_index(op.f('ix_speeches_search_vector'), table_name='speeches', postgresql_using='gin')
    op.drop_index(op.f('speeches_content_tsv_idx'), table_name='speeches', postgresql_using='gin')
    op.drop_constraint(op.f('speeches_unique_statement'), 'speeches', type_='unique')
    op.create_index(op.f('ix_speeches_id'), 'speeches', ['id'], unique=False)
    op.drop_column('speeches', 'search_vector')
    op.drop_column('speeches', 'content_tsv')
    op.drop_column('speeches', 'ai_analysis')
    op.alter_column('vote_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('vote_analyses_vote_id_fkey'), 'vote_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'vote_analyses', 'votes', ['vote_id'], ['id'])
    op.alter_column('vote_results', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('extensions.uuid_generate_v4()'))
    op.alter_column('vote_results', 'result',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_vote_results_mp_id'), table_name='vote_results')
    op.drop_index(op.f('idx_vote_results_vote_id'), table_name='vote_results')
    op.drop_constraint(op.f('vote_results_vote_mp_unique'), 'vote_results', type_='unique')
    op.create_index(op.f('ix_vote_results_id'), 'vote_results', ['id'], unique=False)
    op.drop_constraint(op.f('fk_vote_results_mp'), 'vote_results', type_='foreignkey')
    op.drop_constraint(op.f('fk_vote_results_vote'), 'vote_results', type_='foreignkey')
    op.create_foreign_key(None, 'vote_results', 'mps', ['mp_id'], ['id'])
    op.create_foreign_key(None, 'vote_results', 'votes', ['vote_id'], ['id'])
    op.drop_column('vote_results', 'rebel')
    op.drop_column('vote_results', 'created_at')
    op.alter_column('votes', 'sitting',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'term',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('votes', 'voting_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('votes', 'title_raw',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('votes', 'title_clean',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('votes', 'verdict',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('votes', 'print_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('votes', 'link_sejm',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_index(op.f('idx_votes_bill_id'), table_name='votes')
    op.drop_index(op.f('idx_votes_category'), table_name='votes', postgresql_where='(category IS NOT NULL)')
    op.drop_index(op.f('idx_votes_category_term'), table_name='votes', postgresql_where='(category IS NOT NULL)')
    op.drop_index(op.f('idx_votes_date'), table_name='votes')
    op.drop_index(op.f('idx_votes_importance'), table_name='votes')
    op.drop_index(op.f('idx_votes_print_number'), table_name='votes')
    op.drop_index(op.f('idx_votes_search_vector'), table_name='votes', postgresql_using='gin')
    op.drop_index(op.f('idx_votes_term'), table_name='votes')
    op.drop_index(op.f('idx_votes_title_clean'), table_name='votes')
    op.drop_index(op.f('votes_term_sitting_voting_idx'), table_name='votes')
    op.create_index(op.f('ix_votes_bill_id'), 'votes', ['bill_id'], unique=False)
    op.create_index(op.f('ix_votes_date'), 'votes', ['date'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_print_number'), 'votes', ['print_number'], unique=False)
    op.create_index(op.f('ix_votes_sitting'), 'votes', ['sitting'], unique=False)
    op.create_index(op.f('ix_votes_term'), 'votes', ['term'], unique=False)
    op.create_index(op.f('ix_votes_topic'), 'votes', ['topic'], unique=False)
    op.drop_column('votes', 'cluster_id')
    op.drop_column('votes', 'category')
    op.drop_column('votes', 'name_citizen')
    op.drop_column('votes', 'title_short')
    op.drop_column('votes', 'description')
    op.drop_column('votes', 'importance_score')
    op.drop_column('votes', 'persona_tags')
    op.drop_column('votes', 'is_key_vote')
    op.drop_column('votes', 'topic_tag')
    op.drop_column('votes', 'is_cluster_primary')
    op.drop_column('votes', 'vector_embedding_old')
    op.drop_column('votes', 'ux_category')
    op.drop_column('votes', 'controversy_score')
    op.drop_column('votes', 'semantic_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('semantic_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('controversy_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('ux_category', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('vector_embedding_old', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('is_cluster_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('topic_tag', sa.TEXT(), autoincrement=False, nullable=True, comment='AI-detected topic (e.g. Zdrowie)'))
    op.add_column('votes', sa.Column('is_key_vote', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('persona_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('importance_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='AI-calculated importance (0-100)'))
    op.add_column('votes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('title_short', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('name_citizen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_votes_topic'), table_name='votes')
    op.drop_index(op.f('ix_votes_term'), table_name='votes')
    op.drop_index(op.f('ix_votes_sitting'), table_name='votes')
    op.drop_index(op.f('ix_votes_print_number'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_date'), table_name='votes')
    op.drop_index(op.f('ix_votes_bill_id'), table_name='votes')
    op.create_index(op.f('votes_term_sitting_voting_idx'), 'votes', ['term', 'sitting', 'voting_number'], unique=True)
    op.create_index(op.f('idx_votes_title_clean'), 'votes', ['title_clean'], unique=False)
    op.create_index(op.f('idx_votes_term'), 'votes', ['term'], unique=False)
    op.create_index(op.f('idx_votes_search_vector'), 'votes', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_votes_print_number'), 'votes', ['print_number'], unique=False)
    op.create_index(op.f('idx_votes_importance'), 'votes', [sa.literal_column('importance_score DESC')], unique=False)
    op.create_index(op.f('idx_votes_date'), 'votes', [sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_votes_category_term'), 'votes', ['category', 'term'], unique=False, postgresql_where='(category IS NOT NULL)')
    op.create_index(op.f('idx_votes_category'), 'votes', ['category'], unique=False, postgresql_where='(category IS NOT NULL)')
    op.create_index(op.f('idx_votes_bill_id'), 'votes', ['bill_id'], unique=False)
    op.alter_column('votes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('votes', 'link_sejm',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('votes', 'print_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('votes', 'verdict',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('votes', 'title_clean',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('votes', 'title_raw',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('votes', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('votes', 'voting_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'term',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('votes', 'sitting',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('vote_results', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('vote_results', sa.Column('rebel', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vote_results', type_='foreignkey')
    op.drop_constraint(None, 'vote_results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vote_results_vote'), 'vote_results', 'votes', ['vote_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vote_results_mp'), 'vote_results', 'mps', ['mp_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vote_results_id'), table_name='vote_results')
    op.create_unique_constraint(op.f('vote_results_vote_mp_unique'), 'vote_results', ['vote_id', 'mp_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_vote_results_vote_id'), 'vote_results', ['vote_id'], unique=False)
    op.create_index(op.f('idx_vote_results_mp_id'), 'vote_results', ['mp_id'], unique=False)
    op.alter_column('vote_results', 'result',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('vote_results', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('extensions.uuid_generate_v4()'))
    op.drop_constraint(None, 'vote_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('vote_analyses_vote_id_fkey'), 'vote_analyses', 'votes', ['vote_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vote_analyses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('speeches', sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('speeches', sa.Column('content_tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('speeches', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_speeches_id'), table_name='speeches')
    op.create_unique_constraint(op.f('speeches_unique_statement'), 'speeches', ['mp_id', 'sitting', 'date', 'statement_num'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('speeches_content_tsv_idx'), 'speeches', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_speeches_search_vector'), 'speeches', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_speeches_mp_id_date'), 'speeches', ['mp_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_speeches_date'), 'speeches', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('speeches', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('speeches', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.alter_column('speeches', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speeches', 'speaker_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speeches', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'sitting_summaries', type_='unique')
    op.drop_index(op.f('ix_sitting_summaries_id'), table_name='sitting_summaries')
    op.create_unique_constraint(op.f('sitting_summaries_term_sitting_number_key'), 'sitting_summaries', ['term', 'sitting_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sitting_summaries_term_sitting'), 'sitting_summaries', [sa.literal_column('term DESC'), sa.literal_column('sitting_number DESC')], unique=False)
    op.alter_column('sitting_summaries', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sitting_summaries', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sitting_summaries', 'summary_md',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sitting_summaries', 'sitting_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sitting_summaries', 'term',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('sitting_agendas', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sitting_agendas_sitting_number'), table_name='sitting_agendas')
    op.drop_index(op.f('ix_sitting_agendas_id'), table_name='sitting_agendas')
    op.drop_index(op.f('ix_sitting_agendas_date'), table_name='sitting_agendas')
    op.create_unique_constraint(op.f('sitting_agendas_sitting_number_point_number_title_key'), 'sitting_agendas', ['sitting_number', 'point_number', 'title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sitting_agendas_sitting'), 'sitting_agendas', ['sitting_number'], unique=False)
    op.create_index(op.f('idx_sitting_agendas_date'), 'sitting_agendas', ['date'], unique=False)
    op.alter_column('sitting_agendas', 'print_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sitting_agendas', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sitting_agendas', 'sitting_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_sejm_prints_number'), table_name='sejm_prints')
    op.alter_column('sejm_prints', 'process_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sejm_prints', 'number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_query_embeddings_query'), table_name='query_embeddings')
    op.create_unique_constraint(op.f('query_embeddings_query_key'), 'query_embeddings', ['query'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_query_embeddings_query'), 'query_embeddings', ['query'], unique=False)
    op.alter_column('query_embeddings', 'query',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('mps', sa.Column('declarations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True, comment='List of asset declarations (label, url)'))
    op.drop_index(op.f('ix_mps_term'), table_name='mps')
    op.drop_index(op.f('ix_mps_slug'), table_name='mps')
    op.drop_index(op.f('ix_mps_last_name'), table_name='mps')
    op.drop_index(op.f('ix_mps_id'), table_name='mps')
    op.drop_index(op.f('ix_mps_first_name'), table_name='mps')
    op.drop_index(op.f('ix_mps_club'), table_name='mps')
    op.create_index(op.f('idx_mps_stats_rebellion'), 'mps', ['stats_rebellion'], unique=False)
    op.create_index(op.f('idx_mps_stats_attendance'), 'mps', ['stats_attendance'], unique=False)
    op.create_index(op.f('idx_mps_slug'), 'mps', ['slug'], unique=True)
    op.create_index(op.f('idx_mps_api_id_term'), 'mps', ['api_id', 'term'], unique=True)
    op.create_index(op.f('idx_mps_activity_score'), 'mps', [sa.literal_column('stats_activity_score DESC')], unique=False)
    op.alter_column('mps', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('mps', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('mps', 'link_sejm',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mps', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mps', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment='URL-friendly identifier generated from name (e.g. adam-lubonski)',
               existing_nullable=True)
    op.alter_column('mps', 'seat_number',
               existing_type=sa.INTEGER(),
               comment='Physical seat number in the Sejm Plenary Hall (Digital Twin mapping)',
               existing_nullable=True)
    op.alter_column('mps', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mps', 'term',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('mps', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mps', 'district',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mps', 'club',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mps', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('interpellations', sa.Column('link_sejm', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interpellations', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, ((COALESCE(content, ''::text) || ' '::text) || COALESCE(title, ''::text)))", persisted=True), autoincrement=False, nullable=True))
    op.add_column('interpellations', sa.Column('summary_expert', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interpellations', sa.Column('term', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_interpellations_id'), table_name='interpellations')
    op.create_index(op.f('idx_interpellations_sent_date'), 'interpellations', ['sent_date'], unique=False)
    op.create_index(op.f('idx_interpellations_content_gin'), 'interpellations', ['content_tsv'], unique=False, postgresql_using='gin')
    op.alter_column('interpellations', 'last_modified',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('interpellations', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'interpellation_authors', type_='foreignkey')
    op.drop_constraint(None, 'interpellation_authors', type_='foreignkey')
    op.create_index(op.f('idx_interpellations_mp'), 'interpellation_authors', ['mp_id'], unique=False)
    op.create_index(op.f('idx_interpellation_authors_mp_id'), 'interpellation_authors', ['mp_id'], unique=False)
    op.add_column('euro_votes', sa.Column('vector_embedding_old', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('euro_votes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_euro_votes_id'), table_name='euro_votes')
    op.create_index(op.f('idx_euro_votes_is_key'), 'euro_votes', ['is_key_vote'], unique=False)
    op.create_index(op.f('idx_euro_votes_importance'), 'euro_votes', [sa.literal_column('importance_score DESC')], unique=False)
    op.create_index(op.f('idx_euro_votes_date'), 'euro_votes', [sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('euro_votes_vector_idx'), 'euro_votes', ['vector_embedding'], unique=False, postgresql_ops={'vector_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('euro_votes', 'topic_tag',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('euro_votes', 'term',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('euro_votes', 'date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('euro_votes', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('euro_votes', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('euro_vote_results', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'euro_vote_results', type_='foreignkey')
    op.drop_constraint(None, 'euro_vote_results', type_='foreignkey')
    op.create_foreign_key(op.f('euro_vote_results_mep_id_fkey'), 'euro_vote_results', 'euro_meps', ['mep_id'], ['api_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('euro_vote_results_vote_id_fkey'), 'euro_vote_results', 'euro_votes', ['vote_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_euro_vote_results_id'), table_name='euro_vote_results')
    op.create_index(op.f('idx_euro_vote_results_vote_id'), 'euro_vote_results', ['vote_id'], unique=False)
    op.create_index(op.f('idx_euro_vote_results_mep_id'), 'euro_vote_results', ['mep_id'], unique=False)
    op.alter_column('euro_vote_results', 'vote',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('euro_vote_results', 'mep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('euro_vote_results', 'vote_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('euro_vote_results', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.add_column('euro_meps', sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('euro_meps', sa.Column('total_votes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_euro_meps_id'), table_name='euro_meps')
    op.alter_column('euro_meps', 'term',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('euro_meps', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'eu_group',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'national_party',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('euro_meps', 'country',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Poland'::text"))
    op.alter_column('euro_meps', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('euro_meps', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('committees', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('committees_code_key'), 'committees', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('committees', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committees', 'committee_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committees', 'name_genitive',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committees', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('committees', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'committee_sittings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_committee_sittings_committee'), 'committee_sittings', 'committees', ['committee_code'], ['code'], ondelete='CASCADE')
    op.drop_index(op.f('ix_committee_sittings_status'), table_name='committee_sittings')
    op.drop_index(op.f('ix_committee_sittings_id'), table_name='committee_sittings')
    op.drop_index(op.f('ix_committee_sittings_date'), table_name='committee_sittings')
    op.drop_index(op.f('ix_committee_sittings_committee_code'), table_name='committee_sittings')
    op.create_index(op.f('idx_committee_sittings_status'), 'committee_sittings', ['status'], unique=False)
    op.create_index(op.f('idx_committee_sittings_date'), 'committee_sittings', ['date'], unique=False)
    op.create_index(op.f('idx_committee_sittings_code'), 'committee_sittings', ['committee_code'], unique=False)
    op.create_unique_constraint(op.f('committee_sittings_committee_code_sitting_number_term_key'), 'committee_sittings', ['committee_code', 'sitting_number', 'term'], postgresql_nulls_not_distinct=False)
    op.alter_column('committee_sittings', 'video_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committee_sittings', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committee_sittings', 'room',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committee_sittings', 'sitting_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('committee_sittings', 'committee_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'committee_members', type_='foreignkey')
    op.drop_index(op.f('ix_committee_members_id'), table_name='committee_members')
    op.create_index(op.f('idx_committee_members_mp'), 'committee_members', ['mp_id'], unique=False)
    op.create_index(op.f('idx_committee_members_code'), 'committee_members', ['committee_code'], unique=False)
    op.create_unique_constraint(op.f('committee_members_committee_code_mp_id_from_date_key'), 'committee_members', ['committee_code', 'mp_id', 'from_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('committee_members', 'function',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('committee_members', 'committee_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('categories', sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('name_citizen', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('weight', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_index(op.f('idx_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_index(op.f('idx_categories_parent'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('idx_categories_level'), 'categories', ['level'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'name_pl',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('bills', sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('vector_embedding_old', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bills_type'), table_name='bills')
    op.drop_index(op.f('ix_bills_topic'), table_name='bills')
    op.drop_index(op.f('ix_bills_term'), table_name='bills')
    op.drop_index(op.f('ix_bills_process_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_number'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.create_index(op.f('idx_bills_type'), 'bills', ['type'], unique=False)
    op.create_index(op.f('idx_bills_number'), 'bills', ['number'], unique=False)
    op.drop_index(op.f('ix_asset_declarations_id'), table_name='asset_declarations')
    op.create_unique_constraint(op.f('asset_declarations_mp_id_pdf_url_key'), 'asset_declarations', ['mp_id', 'pdf_url'], postgresql_nulls_not_distinct=False)
    op.alter_column('asset_declarations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('asset_declarations', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('asset_declarations', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('asset_declarations', 'year',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('asset_declarations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_index(op.f('ix_analysis_requests_id'), table_name='analysis_requests')
    op.create_table('topic_arguments',
    sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('keyword', name=op.f('topic_arguments_pkey'))
    )
    op.create_table('speech_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('speech_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.id'], name=op.f('speech_summaries_speech_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speech_summaries_pkey'))
    )
    op.create_table('speech_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('speech_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.id'], name=op.f('speech_tags_speech_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speech_tags_pkey'))
    )
    op.create_table('vote_categories',
    sa.Column('vote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('assigned_by', sa.VARCHAR(length=20), server_default=sa.text("'rule'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("assigned_by::text = ANY (ARRAY['rule'::character varying, 'ai'::character varying, 'manual'::character varying]::text[])", name=op.f('vote_categories_assigned_by_check')),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name=op.f('vote_categories_confidence_check')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('vote_categories_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], name=op.f('vote_categories_vote_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id', 'category_id', name=op.f('vote_categories_pkey'))
    )
    op.create_index(op.f('idx_vote_categories_vote'), 'vote_categories', ['vote_id'], unique=False)
    op.create_index(op.f('idx_vote_categories_primary'), 'vote_categories', ['is_primary'], unique=False, postgresql_where='(is_primary = true)')
    op.create_index(op.f('idx_vote_categories_category'), 'vote_categories', ['category_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parties_pkey'))
    )
    op.create_table('bill_authors',
    sa.Column('bill_process_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], name=op.f('bill_authors_mp_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_process_id', 'mp_id', name=op.f('bill_authors_pkey'))
    )
    op.create_index(op.f('idx_bill_authors_mp_id'), 'bill_authors', ['mp_id'], unique=False)
    op.create_table('club_memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('club_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('club_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('to_date IS NULL OR from_date < to_date', name=op.f('check_dates_logical')),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], name=op.f('club_memberships_mp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('club_memberships_pkey'))
    )
    op.create_index(op.f('idx_club_memberships_unique_current'), 'club_memberships', ['mp_id', 'term'], unique=True, postgresql_where='(to_date IS NULL)')
    op.create_index(op.f('idx_club_memberships_mp'), 'club_memberships', ['mp_id'], unique=False)
    op.create_index(op.f('idx_club_memberships_dates'), 'club_memberships', ['from_date', 'to_date'], unique=False)
    op.create_index(op.f('idx_club_memberships_current'), 'club_memberships', ['mp_id'], unique=False, postgresql_where='(to_date IS NULL)')
    op.create_index(op.f('idx_club_memberships_club_term'), 'club_memberships', ['club_code', 'term'], unique=False, postgresql_where='(to_date IS NULL)')
    op.create_index(op.f('idx_club_memberships_club'), 'club_memberships', ['club_code'], unique=False)
    op.create_table('bill_insights',
    sa.Column('print_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('justification_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('print_number', name=op.f('bill_insights_pkey'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('podsumowania_4',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('print_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['print_number'], ['sejm_prints.number'], name=op.f('podsumowania_4_print_number_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('podsumowania_4_pkey'))
    )
    op.create_table('test_1_mistral',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_1_mistral_pkey'))
    )
    op.create_table('consistency_reports',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('mp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('speech_quote', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("verdict = ANY (ARRAY['Spójny'::text, 'Niespójny'::text, 'Niejednoznaczny'::text])", name=op.f('consistency_reports_verdict_check')),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], name=op.f('consistency_reports_mp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consistency_reports_pkey')),
    sa.UniqueConstraint('mp_id', 'topic', name=op.f('consistency_reports_mp_id_topic_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('processes',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ue', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('print_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('process_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('change_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stages_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, ((COALESCE(description, ''::text) || ' '::text) || COALESCE(title, ''::text)))", persisted=True), autoincrement=False, nullable=True),
    sa.Column('simple_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ux_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('who_affected', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('processes_pkey'))
    )
    op.create_index(op.f('idx_processes_description_gin'), 'processes', ['description_tsv'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
