-- Migration: Bulk update social media links for KO MPs
-- Date: 2025-12-26
-- Generated from user-provided data

UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/AdamKrzeminskiPoselNaSejmRP/"}'::jsonb WHERE name = 'Adam Krzemiński';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/adamszlapka/", "twitter": "https://x.com/adamSzlapka"}'::jsonb WHERE name = 'Adam Szłapka';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/AdrianWitczakTM/"}'::jsonb WHERE name = 'Adrian Witczak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/hanajczykagnieszka/"}'::jsonb WHERE name = 'Agnieszka Hanajczyk';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/apomaska/", "website": "https://www.pomaska.pl"}'::jsonb WHERE name = 'Agnieszka Pomaska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/jasnezegajewska/", "twitter": "https://x.com/AGajewska"}'::jsonb WHERE name = 'Aleksandra Gajewska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/3olakot/"}'::jsonb WHERE name = 'Aleksandra Kot';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/aleksandra.wisniewska.75248/"}'::jsonb WHERE name = 'Aleksandra Uznańska-Wiśniewska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/prof.alicja.chybicka/"}'::jsonb WHERE name = 'Alicja Chybicka';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/p/Alicja-%C5%81epkowska-Go%C5%82a%C5%9B-Pos%C5%82anka-na-Sejm-RP-100064645455889/"}'::jsonb WHERE name = 'Alicja Łepkowska-Gołaś';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/aalicjaluczak/"}'::jsonb WHERE name = 'Alicja Łuczak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/AndrzejDomanskiPolityk/"}'::jsonb WHERE name = 'Andrzej Domański';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/sobolakannadosejmu/"}'::jsonb WHERE name = 'Anna Sobolak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/AnnaWojciechowska.Elk/"}'::jsonb WHERE name = 'Anna Wojciechowska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/tajner.apoloniusz/"}'::jsonb WHERE name = 'Apoloniusz Tajner';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/marchewka.arkadiusz/", "website": "https://arkadiuszmarchewka.pl"}'::jsonb WHERE name = 'Arkadiusz Marchewka';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/A.Myrcha/"}'::jsonb WHERE name = 'Arkadiusz Myrcha';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/artur.gierada/"}'::jsonb WHERE name = 'Artur Gierada';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/ArturLacki4/"}'::jsonb WHERE name = 'Artur Łącki';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/BDolniak/"}'::jsonb WHERE name = 'Barbara Dolniak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/GrygorcewiczBarbara/"}'::jsonb WHERE name = 'Barbara Grygorcewicz';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/BarbaraANowacka/", "twitter": "https://x.com/barbaraanowacka"}'::jsonb WHERE name = 'Barbara Nowacka';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/zawiejabartosz/"}'::jsonb WHERE name = 'Bartosz Zawieja';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/BoguslawWoloszanskiKandydat/"}'::jsonb WHERE name = 'Bogusław Wołoszański';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/bozena.lisowska/"}'::jsonb WHERE name = 'Bożena Lisowska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/pages/Cezary-Tomczyk/100044403787048/", "website": "https://cezarytomczyk.pl"}'::jsonb WHERE name = 'Cezary Tomczyk';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/CzeslawMroczek/", "website": "https://www.czeslawmroczek.pl"}'::jsonb WHERE name = 'Czesław Mroczek';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/djazlowiecka/"}'::jsonb WHERE name = 'Danuta Jazłowiecka';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/radny.jaskowiec/"}'::jsonb WHERE name = 'Dominik Jaśkowiec';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/donaldtusk/", "twitter": "https://x.com/donaldtusk"}'::jsonb WHERE name = 'Donald Tusk';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/Dor.Loboda/"}'::jsonb WHERE name = 'Dorota Łoboda';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/DorotaMarekPoslankaRP/"}'::jsonb WHERE name = 'Dorota Marek';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/elzbieta.gapinska/"}'::jsonb WHERE name = 'Elżbieta Gapińska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/elzbietagelert/"}'::jsonb WHERE name = 'Elżbieta Gelert';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/elzbieta.anna.polak/"}'::jsonb WHERE name = 'Elżbieta Polak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/ewakolodziej.posel/"}'::jsonb WHERE name = 'Ewa Kołodziej';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/FranekSterczewski/", "twitter": "https://x.com/f_sterczewski"}'::jsonb WHERE name = 'Franciszek Sterczewski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/poselgabrielalenartowicz/"}'::jsonb WHERE name = 'Gabriela Lenartowicz';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/gnapieralski/"}'::jsonb WHERE name = 'Grzegorz Napieralski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/szopinskihenryk/"}'::jsonb WHERE name = 'Henryk Szopiński';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/henrykakrzywonos/"}'::jsonb WHERE name = 'Henryka Krzywonos-Strycharska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/PoslankaHartwich/"}'::jsonb WHERE name = 'Iwona Hartwich';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/iwonakarolewska.swiecie/"}'::jsonb WHERE name = 'Iwona Karolewska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/sprawdzonawdzialaniu/"}'::jsonb WHERE name = 'Iwona Krawczyk';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/I.Leszczyna/", "twitter": "https://x.com/Leszczyna", "website": "https://leszczyna.info"}'::jsonb WHERE name = 'Izabela Leszczyna';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/jacek.karnowski/"}'::jsonb WHERE name = 'Jacek Karnowski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/JanGrabiecLegionowo/", "website": "https://jangrabiec.pl"}'::jsonb WHERE name = 'Jan Grabiec';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/cichon.janusz/"}'::jsonb WHERE name = 'Janusz Cichoń';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/PoselUrbaniak/"}'::jsonb WHERE name = 'Jarosław Urbaniak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/Walesa.Jaroslaw/"}'::jsonb WHERE name = 'Jarosław Wałęsa';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/meysztowicz.jerzy/"}'::jsonb WHERE name = 'Jerzy Meysztowicz';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/PoselNaSejmRP.JoannaFrydrych/"}'::jsonb WHERE name = 'Joanna Frydrych';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/KluzikRostkowska/"}'::jsonb WHERE name = 'Joanna Kluzik-Rostkowska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/JolantaNiezgodzka/"}'::jsonb WHERE name = 'Jolanta Niezgodzka';
UPDATE mps SET contact_info = contact_info || '{"website": "https://karolinapawliczak.pl"}'::jsonb WHERE name = 'Karolina Pawliczak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/JachiraKlaudia/", "twitter": "https://x.com/JachiraKlaudia"}'::jsonb WHERE name = 'Klaudia Jachira';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/konrad.frysztak.RADOM/", "website": "https://frysztak.eu"}'::jsonb WHERE name = 'Konrad Frysztak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/radnykrystianluczak/"}'::jsonb WHERE name = 'Krystian Łuczak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/k.sibinska/"}'::jsonb WHERE name = 'Krystyna Sibińska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/LiderPoNaPodkarpaciu/"}'::jsonb WHERE name = 'Krystyna Skowrońska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/krystynaszumilas/"}'::jsonb WHERE name = 'Krystyna Szumilas';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/bojarskikrzysztof/"}'::jsonb WHERE name = 'Krzysztof Bojarski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/gadowskipl/", "website": "https://gadowski.pl"}'::jsonb WHERE name = 'Krzysztof Gadowski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/kgrabczuk/"}'::jsonb WHERE name = 'Krzysztof Grabczuk';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/StarostaKrzysztofHabura/"}'::jsonb WHERE name = 'Krzysztof Habura';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/MieszkowskiK/"}'::jsonb WHERE name = 'Krzysztof Mieszkowski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/PiatkowskiKrzysztof/"}'::jsonb WHERE name = 'Krzysztof Piątkowski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/ktruskolaski/"}'::jsonb WHERE name = 'Krzysztof Truskolaski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/lukaszhorbatowskiPO/"}'::jsonb WHERE name = 'Łukasz Horbatowski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/MaciejLasek.KO/", "twitter": "https://x.com/LasekMaciej"}'::jsonb WHERE name = 'Maciej Lasek';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/tomczykiewiczmaciej/"}'::jsonb WHERE name = 'Maciej Tomczykiewicz';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/maciejwrobelofficial/"}'::jsonb WHERE name = 'Maciej Wróbel';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/FiliksMagdalena/"}'::jsonb WHERE name = 'Magdalena Filiks';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/magdalenakolodziejczakposlankadosejmurp/"}'::jsonb WHERE name = 'Magdalena Kołodziejczak';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/LoskoMagdalena/"}'::jsonb WHERE name = 'Magdalena Łośko';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/roguskamagdalena/"}'::jsonb WHERE name = 'Magdalena Roguska';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/malgorzatagromadzkapl/"}'::jsonb WHERE name = 'Małgorzata Gromadzka';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/MalgosiaNiemczyk/"}'::jsonb WHERE name = 'Małgorzata Niemczyk';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/malgorzata.pepek/"}'::jsonb WHERE name = 'Małgorzata Pępek';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/GoTracz/"}'::jsonb WHERE name = 'Małgorzata Tracz';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/MarcinRBosacki/"}'::jsonb WHERE name = 'Marcin Bosacki';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/WojtGminyDzierzoniow/"}'::jsonb WHERE name = 'Marek Chmielewski';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/prof.marekgzik/"}'::jsonb WHERE name = 'Marek Gzik';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/marek.hok/"}'::jsonb WHERE name = 'Marek Hok';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/KrzakalaMarek/"}'::jsonb WHERE name = 'Marek Krząkała';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/mareksowa.fanpage/"}'::jsonb WHERE name = 'Marek Sowa';
UPDATE mps SET contact_info = contact_info || '{"facebook": "https://www.facebook.com/RosaMonikaAnna/"}'::jsonb WHERE name = 'Monika Rosa';