-- Migration: Update Complete Social Media links for PiS MPs
-- Date: 2025-12-26
-- Adds verified Facebook and Twitter/X links from official table

UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/PoselAndrzejAdamczyk/"}'::jsonb WHERE name = 'Andrzej Adamczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/gawronandrzej/"}'::jsonb WHERE name = 'Andrzej Gawron' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/andrzej.gutmostowy/"}'::jsonb WHERE name = 'Andrzej Gut-Mostowy' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/kosztowniak/"}'::jsonb WHERE name = 'Andrzej Kosztowniak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/andrzej.kryj/"}'::jsonb WHERE name = 'Andrzej Kryj' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/AndrzejSliwka88/"}'::jsonb WHERE name = 'Andrzej Śliwka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/czerwinskaanita/"}'::jsonb WHERE name = 'Anita Czerwińska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/posel.AnnaBaluch/"}'::jsonb WHERE name = 'Anna Baluch' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/a.dabrowska.banaszek/"}'::jsonb WHERE name = 'Anna Dąbrowska-Banaszek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/AnnaGembickaPL/", "twitter": "https://x.com/AnnaGembicka"}'::jsonb WHERE name = 'Anna Gembicka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/poselannakrupka/", "twitter": "https://x.com/AnnaMKrupka"}'::jsonb WHERE name = 'Anna Krupka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/Anna.Kwiecien.Radom/"}'::jsonb WHERE name = 'Anna Kwiecień' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/anna.milczanowska/"}'::jsonb WHERE name = 'Anna Milczanowska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/AnnaPieczarkaPiS/"}'::jsonb WHERE name = 'Anna Pieczarka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/Macierewicz_A"}'::jsonb WHERE name = 'Antoni Macierewicz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/arkadiusz.mularczyk/"}'::jsonb WHERE name = 'Arkadiusz Mularczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/poselbarbarabartus/"}'::jsonb WHERE name = 'Barbara Bartuś' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/wroblewski.bartlomiej/"}'::jsonb WHERE name = 'Bartłomiej Wróblewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KownackiBartosz"}'::jsonb WHERE name = 'Bartosz Kownacki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/boleslawpiechapis/"}'::jsonb WHERE name = 'Bolesław Piecha' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/czeslawhocprywatne/"}'::jsonb WHERE name = 'Czesław Hoc' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/milewskidaniel/"}'::jsonb WHERE name = 'Daniel Milewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/DariuszMateckiFanPage/", "twitter": "https://x.com/DariuszMatecki"}'::jsonb WHERE name = 'Dariusz Matecki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/DariuszPiontkowski/"}'::jsonb WHERE name = 'Dariusz Piontkowski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/stefaniukoficjalnie/"}'::jsonb WHERE name = 'Dariusz Stefaniuk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/chorosinskaPL/"}'::jsonb WHERE name = 'Dominika Chorosińska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/EdwardSiarka/", "twitter": "https://x.com/ESiarka"}'::jsonb WHERE name = 'Edward Siarka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/EWitek.Sejm/"}'::jsonb WHERE name = 'Elżbieta Witek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/LeniartEwa/"}'::jsonb WHERE name = 'Ewa Leniart' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/Posel.Ewa.Malik/"}'::jsonb WHERE name = 'Ewa Malik' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/Kapinos.Fryderyk/"}'::jsonb WHERE name = 'Fryderyk Kapinos' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/grzegorzgazadosejmu/"}'::jsonb WHERE name = 'Grzegorz Gaża' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/galorek/"}'::jsonb WHERE name = 'Grzegorz Lorek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/MatusiakGrzegorz/"}'::jsonb WHERE name = 'Grzegorz Matusiak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/piechowiakPL/"}'::jsonb WHERE name = 'Grzegorz Piechowiak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/ministerpuda/", "twitter": "https://x.com/GrzegorzPuda"}'::jsonb WHERE name = 'Grzegorz Puda' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/grzegorz.adam.wozniak/"}'::jsonb WHERE name = 'Grzegorz Woźniak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/HenrykKowalczyk/"}'::jsonb WHERE name = 'Henryk Kowalczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/hubertjablonskioff/"}'::jsonb WHERE name = 'Hubert Jabłoński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/Zyska.Ireneusz/"}'::jsonb WHERE name = 'Ireneusz Zyska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/IwonaArent"}'::jsonb WHERE name = 'Iwona Arent' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/jacekboguckipl/"}'::jsonb WHERE name = 'Jacek Bogucki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/OzdobaJacek/", "twitter": "https://x.com/OzdobaJacek"}'::jsonb WHERE name = 'Jacek Ozdoba' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/jacek.sasin.1/", "twitter": "https://x.com/SasinJacek"}'::jsonb WHERE name = 'Jacek Sasin' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/JacekSwiat/"}'::jsonb WHERE name = 'Jacek Świat' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/dziedziczak.jan/"}'::jsonb WHERE name = 'Jan Dziedziczak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JanKanthak"}'::jsonb WHERE name = 'Jan Kanthak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MosinskiJan"}'::jsonb WHERE name = 'Jan Mosiński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/CieszynskiJanusz/", "twitter": "https://x.com/jciesz"}'::jsonb WHERE name = 'Janusz Cieszyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/JanuszKowalski.official/", "twitter": "https://x.com/JKowalski_posel"}'::jsonb WHERE name = 'Janusz Kowalski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/OficjalnyJK"}'::jsonb WHERE name = 'Jarosław Kaczyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/wybierzKrajewskiego/", "twitter": "https://x.com/KrajewskiJarek"}'::jsonb WHERE name = 'Jarosław Krajewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/jsachajko/"}'::jsonb WHERE name = 'Jarosław Sachajko' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/jaroslaw.sellin/"}'::jsonb WHERE name = 'Jarosław Sellin' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/ZielinskiJaro/", "twitter": "https://x.com/ZielinskiJaro"}'::jsonb WHERE name = 'Jarosław Zieliński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/maleckij/"}'::jsonb WHERE name = 'Jerzy Małecki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/JerzyMaterna/"}'::jsonb WHERE name = 'Jerzy Materna' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/jerzy.stanislaw.paul/"}'::jsonb WHERE name = 'Jerzy Paul' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/JerzyPolaczek/"}'::jsonb WHERE name = 'Jerzy Polaczek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BorowiakJoanna"}'::jsonb WHERE name = 'Joanna Borowiak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/jozefaszczurekzelazko/"}'::jsonb WHERE name = 'Józefa Szczurek-Żelazko' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KacperPlazynski"}'::jsonb WHERE name = 'Kacper Płażyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/poselBortniczuk/"}'::jsonb WHERE name = 'Kamil Bortniczuk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/PoselKatarzynaSojka/", "twitter": "https://x.com/aK_Sojka"}'::jsonb WHERE name = 'Katarzyna Sójka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/kazimierz.gwiazdowski/"}'::jsonb WHERE name = 'Kazimierz Gwiazdowski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/Kazimierz.Smolinski11/"}'::jsonb WHERE name = 'Kazimierz Smoliński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/cieciorakrzysztof/"}'::jsonb WHERE name = 'Krzysztof Ciecióra' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/gluchowskikrzysztof/"}'::jsonb WHERE name = 'Krzysztof Głuchowski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/poselzaglebiamiedziowego/"}'::jsonb WHERE name = 'Krzysztof Kubów' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/posel.krzysztof.lipiec/"}'::jsonb WHERE name = 'Krzysztof Lipiec' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KrzSzczucki"}'::jsonb WHERE name = 'Krzysztof Szczucki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/prof.krzysztofszulowski/"}'::jsonb WHERE name = 'Krzysztof Szulowski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/LukaszSchreiber/"}'::jsonb WHERE name = 'Łukasz Schreiber' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/PoselMariuszBlaszczak/"}'::jsonb WHERE name = 'Mariusz Błaszczak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MorawieckiM"}'::jsonb WHERE name = 'Mateusz Morawiecki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/paweljabIonski/", "twitter": "https://x.com/paweljablonski_"}'::jsonb WHERE name = 'Paweł Jabłoński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KrolPiotr1"}'::jsonb WHERE name = 'Piotr Król' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/RadoslawFogiel/"}'::jsonb WHERE name = 'Radosław Fogiel' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/zbhoffmann/"}'::jsonb WHERE name = 'Zbigniew Hoffmann' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ZiobroPL"}'::jsonb WHERE name = 'Zbigniew Ziobro' AND term = 10;