-- Migration: Update Mega-Ultra-Complete 77 PiS Social accounts
-- Date: 2025-12-26

UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/AnnaGembicka", "facebook": "https://www.facebook.com/AnnaGembickaPL/"}'::jsonb WHERE name = 'Anna Gembicka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/AnnaMKrupka", "facebook": "https://www.facebook.com/poselannakrupka/"}'::jsonb WHERE name = 'Anna Krupka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/Macierewicz_A"}'::jsonb WHERE name = 'Antoni Macierewicz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/arekmularczyk", "facebook": "https://www.facebook.com/arkadiusz.mularczyk/"}'::jsonb WHERE name = 'Arkadiusz Mularczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KownackiBartosz"}'::jsonb WHERE name = 'Bartosz Kownacki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BoleslawPiecha", "facebook": "https://www.facebook.com/boleslawpiechapis/"}'::jsonb WHERE name = 'Bolesław Piecha' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/czeslawhoc", "facebook": "https://www.facebook.com/czeslawhocprywatne/"}'::jsonb WHERE name = 'Czesław Hoc' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/DanielMilewski", "facebook": "https://www.facebook.com/milewskidaniel/"}'::jsonb WHERE name = 'Daniel Milewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/DariuszMatecki", "facebook": "https://www.facebook.com/DariuszMateckiFanPage/"}'::jsonb WHERE name = 'Dariusz Matecki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/DariuszStefani9", "facebook": "https://www.facebook.com/stefaniukoficjalnie/"}'::jsonb WHERE name = 'Dariusz Stefaniuk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/chorosinska", "facebook": "https://www.facebook.com/chorosinskaPL/"}'::jsonb WHERE name = 'Dominika Chorosińska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ESiarka", "facebook": "https://www.facebook.com/EdwardSiarka/"}'::jsonb WHERE name = 'Edward Siarka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/EwaLeniart", "facebook": "https://www.facebook.com/LeniartEwa/"}'::jsonb WHERE name = 'Ewa Leniart' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MalikDanutaEwa", "facebook": "https://www.facebook.com/Posel.Ewa.Malik/"}'::jsonb WHERE name = 'Ewa Malik' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/GrzegorzGaza", "facebook": "https://www.facebook.com/grzegorzgazadosejmu/"}'::jsonb WHERE name = 'Grzegorz Gaża' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/glorekposel", "facebook": "https://www.facebook.com/galorek/"}'::jsonb WHERE name = 'Grzegorz Lorek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/GrzegorzMatusi1", "facebook": "https://www.facebook.com/MatusiakGrzegorz/"}'::jsonb WHERE name = 'Grzegorz Matusiak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/piechowiakPL", "facebook": "https://www.facebook.com/piechowiakPL/"}'::jsonb WHERE name = 'Grzegorz Piechowiak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/GrzegorzPuda", "facebook": "https://www.facebook.com/ministerpuda/"}'::jsonb WHERE name = 'Grzegorz Puda' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/Poselwozniak", "facebook": "https://www.facebook.com/grzegorz.adam.wozniak/"}'::jsonb WHERE name = 'Grzegorz Woźniak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/Kowalczyk_H", "facebook": "https://www.facebook.com/HenrykKowalczyk/"}'::jsonb WHERE name = 'Henryk Kowalczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/IwonaArent"}'::jsonb WHERE name = 'Iwona Arent' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JackBogucki", "facebook": "https://www.facebook.com/jacekboguckipl/"}'::jsonb WHERE name = 'Jacek Bogucki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/OzdobaJacek", "facebook": "https://www.facebook.com/OzdobaJacek/"}'::jsonb WHERE name = 'Jacek Ozdoba' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/SasinJacek", "facebook": "https://www.facebook.com/jacek.sasin.1/"}'::jsonb WHERE name = 'Jacek Sasin' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JacekSwiat", "facebook": "https://www.facebook.com/JacekSwiat/"}'::jsonb WHERE name = 'Jacek Świat' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JanKanthak"}'::jsonb WHERE name = 'Jan Kanthak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MosinskiJan"}'::jsonb WHERE name = 'Jan Mosiński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/jciesz", "facebook": "https://www.facebook.com/CieszynskiJanusz/"}'::jsonb WHERE name = 'Janusz Cieszyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JKowalski_posel", "facebook": "https://www.facebook.com/JanuszKowalski.official/"}'::jsonb WHERE name = 'Janusz Kowalski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/OficjalnyJK"}'::jsonb WHERE name = 'Jarosław Kaczyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KrajewskiJarek", "facebook": "https://www.facebook.com/wybierzKrajewskiego/"}'::jsonb WHERE name = 'Jarosław Krajewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/jsachajko", "facebook": "https://www.facebook.com/jsachajko/"}'::jsonb WHERE name = 'Jarosław Sachajko' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JaroslawSellin", "facebook": "https://www.facebook.com/jaroslaw.sellin/"}'::jsonb WHERE name = 'Jarosław Sellin' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ZielinskiJaro", "facebook": "https://www.facebook.com/ZielinskiJaro/"}'::jsonb WHERE name = 'Jarosław Zieliński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/jerzy_paul", "facebook": "https://www.facebook.com/jerzy.stanislaw.paul/"}'::jsonb WHERE name = 'Jerzy Paul' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/JerzyPolaczek", "facebook": "https://www.facebook.com/JerzyPolaczek/"}'::jsonb WHERE name = 'Jerzy Polaczek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BorowiakJoanna"}'::jsonb WHERE name = 'Joanna Borowiak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KacperPlazynski"}'::jsonb WHERE name = 'Kacper Płażyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KamilBortniczuk", "facebook": "https://www.facebook.com/poselBortniczuk/"}'::jsonb WHERE name = 'Kamil Bortniczuk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/aK_Sojka", "facebook": "https://www.facebook.com/PoselKatarzynaSojka/"}'::jsonb WHERE name = 'Katarzyna Sójka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KrzysztofLipiec", "facebook": "https://www.facebook.com/posel.krzysztof.lipiec/"}'::jsonb WHERE name = 'Krzysztof Lipiec' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KrzSzczucki"}'::jsonb WHERE name = 'Krzysztof Szczucki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MarcinPGwozdz"}'::jsonb WHERE name = 'Marcin Gwóźdź' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MarcinOciepa", "facebook": "https://www.facebook.com/Mar.Ociepa/"}'::jsonb WHERE name = 'Marcin Ociepa' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/marcin_przydacz", "facebook": "https://www.facebook.com/marcin.przydacz2015/"}'::jsonb WHERE name = 'Marcin Przydacz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MarekKuchcinski"}'::jsonb WHERE name = 'Marek Kuchciński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/matuszewski1408"}'::jsonb WHERE name = 'Marek Matuszewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/mareksuski"}'::jsonb WHERE name = 'Marek Suski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MarekWesoly"}'::jsonb WHERE name = 'Marek Wesoły' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MariaKurowskaPL"}'::jsonb WHERE name = 'Maria Kurowska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MariuszGosek"}'::jsonb WHERE name = 'Mariusz Gosek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MorawieckiM"}'::jsonb WHERE name = 'Mateusz Morawiecki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/michaldworczyk"}'::jsonb WHERE name = 'Michał Dworczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/Michal_Moskal"}'::jsonb WHERE name = 'Michał Moskal' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/mwojcik_"}'::jsonb WHERE name = 'Michał Wójcik' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MWosPL"}'::jsonb WHERE name = 'Michał Woś' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/N_Kaczmarczyk"}'::jsonb WHERE name = 'Norbert Kaczmarczyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/paweljablonski_", "facebook": "https://www.facebook.com/paweljabIonski/"}'::jsonb WHERE name = 'Paweł Jabłoński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/PiotrGlinski"}'::jsonb WHERE name = 'Piotr Gliński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/piotr_kaleta_", "facebook": "https://www.facebook.com/piotr.kaleta.pis/"}'::jsonb WHERE name = 'Piotr Kaleta' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KrolPiotr1"}'::jsonb WHERE name = 'Piotr Król' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/poselpiotrpolak"}'::jsonb WHERE name = 'Piotr Polak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/uruskipiotr"}'::jsonb WHERE name = 'Piotr Uruski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/CzarnekP"}'::jsonb WHERE name = 'Przemysław Czarnek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/DrabekBB", "facebook": "https://www.facebook.com/PrzemyslawDrabekBB/"}'::jsonb WHERE name = 'Przemysław Drabek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/RafalBochenek"}'::jsonb WHERE name = 'Rafał Bochenek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/R_Romanowski1"}'::jsonb WHERE name = 'Rafał Romanowski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/gontarz93"}'::jsonb WHERE name = 'Robert Gontarz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/RobertTelus"}'::jsonb WHERE name = 'Robert Telus' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BartosikRyszard"}'::jsonb WHERE name = 'Ryszard Bartosik' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/RyszardTerlecki"}'::jsonb WHERE name = 'Ryszard Terlecki' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/sjkaleta"}'::jsonb WHERE name = 'Sebastian Kaleta' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/SkwarekSlawomir"}'::jsonb WHERE name = 'Sławomir Skwarek' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/SzymonGizynski"}'::jsonb WHERE name = 'Szymon Giżyński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ZiobroPL"}'::jsonb WHERE name = 'Zbigniew Ziobro' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/wassermann_ma", "facebook": "https://www.facebook.com/malgorzata.wassermann/"}'::jsonb WHERE name = 'Małgorzata Wassermann' AND term = 10;