-- Migration: Update Social accounts for Polska 2050
-- Date: 2025-12-26

UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/GomolaAdam", "facebook": "https://www.facebook.com/GomolaAdam/"}'::jsonb WHERE name = 'Adam Gomoła' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/AdamLubonski", "facebook": "https://www.facebook.com/adamlubonski2050/"}'::jsonb WHERE name = 'Adam Luboński' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/aga_buczynska", "facebook": "https://www.facebook.com/a.buczynskaPL2050/"}'::jsonb WHERE name = 'Agnieszka Buczyńska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/AleksandraLeo", "facebook": "https://www.facebook.com/p/Aleksandra-Leo/"}'::jsonb WHERE name = 'Aleksandra Leo' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BarbaraOkula", "facebook": "https://www.facebook.com/BarbaraOkulaPolska2050/"}'::jsonb WHERE name = 'Barbara Okuła' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BaszkaOli", "facebook": "https://www.facebook.com/BarbaraOliwiecka/"}'::jsonb WHERE name = 'Barbara Oliwiecka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/romowiczbartosz", "facebook": "https://www.facebook.com/romowicz.bartosz/"}'::jsonb WHERE name = 'Bartosz Romowicz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ElaBurkiewicz", "facebook": "https://www.facebook.com/ela.burkiewicz/"}'::jsonb WHERE name = 'Elżbieta Burkiewicz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/SchaedlerEwa", "facebook": "https://www.facebook.com/ewa.schaedler.PL2050/"}'::jsonb WHERE name = 'Ewa Schädler' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/Szymanowska2050", "facebook": "https://www.facebook.com/EwaSzymanowskaPolska2050/"}'::jsonb WHERE name = 'Ewa Szymanowska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/BodnarIzabela", "facebook": "https://www.facebook.com/poslanka.izabela.bodnar/"}'::jsonb WHERE name = 'Izabela Bodnar' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/joannamucha", "facebook": "https://www.facebook.com/joannamucha/"}'::jsonb WHERE name = 'Joanna Mucha' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/KamilWnuk22", "facebook": "https://www.facebook.com/kamilwnukpl/"}'::jsonb WHERE name = 'Kamil Wnuk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/LukaszOsmalak", "facebook": "https://www.facebook.com/OsmalakLukasz/"}'::jsonb WHERE name = 'Łukasz Osmalak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/nmaja", "facebook": "https://www.facebook.com/majanowaklubuskie/"}'::jsonb WHERE name = 'Maja Nowak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/m_skonieczka", "facebook": "https://www.facebook.com/m.skonieczka/"}'::jsonb WHERE name = 'Marcin Skonieczka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/McGramat", "facebook": "https://www.facebook.com/gramatyka.michal/"}'::jsonb WHERE name = 'Michał Gramatyka' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/michalkobosko", "facebook": "https://www.facebook.com/michalkoboskoofficial/"}'::jsonb WHERE name = 'Michał Kobosko' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/MiroslawSuchon", "facebook": "https://www.facebook.com/MiroslawSuchon/"}'::jsonb WHERE name = 'Mirosław Suchoń' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/NPietrykowski50", "facebook": "https://www.facebook.com/n.pietrykowski50/"}'::jsonb WHERE name = 'Norbert Pietrykowski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/hennigkloska", "facebook": "https://www.facebook.com/PaulinaHennigKloskaPolska2050/"}'::jsonb WHERE name = 'Paulina Hennig-Kloska' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/SlizPawel", "facebook": "https://www.facebook.com/SlizPawel/"}'::jsonb WHERE name = 'Paweł Śliz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ZalewskiPawel", "facebook": "https://www.facebook.com/PoselPawelZalewski/"}'::jsonb WHERE name = 'Paweł Zalewski' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"facebook": "https://www.facebook.com/gornikiewicz/"}'::jsonb WHERE name = 'Piotr Górnikiewicz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/strach_piotr", "facebook": "https://www.facebook.com/piotr.strach/"}'::jsonb WHERE name = 'Piotr Strach' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/kasp_rafa", "facebook": "https://www.facebook.com/100076001604311/"}'::jsonb WHERE name = 'Rafał Kasprzyk' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/RKomarewicz", "facebook": "https://www.facebook.com/Komarewicz/"}'::jsonb WHERE name = 'Rafał Komarewicz' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/RyszardPetru", "facebook": "https://www.facebook.com/PetruRyszard/"}'::jsonb WHERE name = 'Ryszard Petru' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/S_Cwik", "facebook": "https://www.facebook.com/cwikslawomir/"}'::jsonb WHERE name = 'Sławomir Ćwik' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/szymon_holownia", "facebook": "https://www.facebook.com/PL2050SzymonaHolowni/"}'::jsonb WHERE name = 'Szymon Hołownia' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/WioletaTomczak", "facebook": "https://www.facebook.com/WioletaTomczakGdynia/"}'::jsonb WHERE name = 'Wioleta Tomczak' AND term = 10;
UPDATE mps SET contact_info = COALESCE(contact_info, '{}'::jsonb) || '{"twitter": "https://x.com/ZanetaSliwowska", "facebook": "https://www.facebook.com/p/Żaneta-Cwalina-Śliwowska-Polska-2050-100092578028273/"}'::jsonb WHERE name = 'Żaneta Cwalina-Śliwowska' AND term = 10;