-- Add created_at column to primary tables
ALTER TABLE mps ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE votes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE bills ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE interpellations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
