// ============================================================================
// EXPANDED SEMANTIC CONTEXT MAP (Auto-generated)
// Total mappings: 147
// ============================================================================

export const EXPANDED_CONTEXT_MAP: Record<string, string[]> = {
  '5g': ['sieć', 'telefonia', 'internet', 'maszty'],
  'abonament': ['rtv', 'telewizja', 'radio', 'opłata', 'media publiczne', 'krrit'],
  'abw': ['służby', 'bezpieczeństwo', 'kontrwywiad', 'terroryzm'],
  'adopcja': ['dziecko', 'rodzina', 'sąd', 'opieka'],
  'adwokat': ['obrońca', 'sąd', 'prawnik', 'pełnomocnik'],
  'alimenty': ['dziecko', 'rozwód', 'rodzic', 'sąd', 'egzekucja'],
  'alkohol': ['sprzedaż', 'reklama', 'wiek', 'promocja'],
  'antyszczepionkowcy': ['szczepienia', 'ruch', 'protest', 'zdrowie'],
  'apteka': ['lek', 'farmaceuta', 'recepta', 'refundacja'],
  'areszt': ['zatrzymanie', 'podejrzany', 'sąd', 'prokurator'],
  'arimr': ['dopłaty', 'rolnictwo', 'modernizacja', 'dotacje'],
  'atom': ['elektrownia', 'jądrowa', 'energia', 'paliwo'],
  'autostrada': ['droga', 'viaTOLL', 'opłata', 'budowa'],
  'becikowe': ['dziecko', 'narodziny', 'świadczenie', 'rodzice'],
  'bhp': ['praca', 'bezpieczeństwo', 'wypadek', 'szkolenie'],
  'burmistrz': ['miasto', 'wybory', 'samorząd', 'gmina'],
  'cba': ['korupcja', 'śledztwo', 'urzędnik', 'przestępstwo'],
  'cpk': ['lotnisko', 'inwestycja', 'kolej', 'warszawa'],
  'cyberbezpieczeństwo': ['ataki', 'hakerzy', 'ochrona', 'infrastruktura'],
  'cyfryzacja': ['internet', 'e-usługi', 'epuap', 'mObywatel'],
  'czternastka': ['emerytura', 'świadczenie', 'bonus', 'zus'],
  'diagnoza': ['badanie', 'lekarz', 'choroba', 'leczenie'],
  'dobrostan': ['zwierzęta', 'hodowla', 'przepisy', 'ue'],
  'doktorant': ['uczelnia', 'nauka', 'badania', 'stypendium'],
  'dom dziecka': ['sierota', 'opieka', 'adopcja', 'pieczy'],
  'dopłaty': ['rolnik', 'arimr', 'ue', 'hektar', 'produkcja'],
  'dotacja': ['wsparcie', 'dofinansowanie', 'program', 'pomoc', 'budżet'],
  'egzamin': ['matura', 'szkoła', 'ocena', 'test', 'kwalifikacje'],
  'ekspresówka': ['droga', 'budowa', 'transport', 's'],
  'emeryt': ['senior', 'zus', 'renta', 'świadczenie'],
  'epuap': ['elektroniczny', 'urząd', 'podpis', 'profil'],
  'ets': ['emisja', 'co2', 'uprawnienia', 'handel'],
  'eutanazja': ['śmierć', 'godna', 'medycyna', 'prawo'],
  'filharmonia': ['muzyka', 'kultura', 'orkiestra', 'koncert'],
  'fotowoltaika': ['słońce', 'panele', 'energia', 'oze', 'prosument'],
  'frankowicz': ['kredyt', 'bank', 'hipoteka', 'kurs', 'waluta', 'chf'],
  'fundusz': ['inwestycje', 'pieniądze', 'kapitał', 'dotacja', 'subwencja'],
  'funduszu': ['inwestycje', 'pieniądze', 'kapitał', 'dotacja', 'subwencja'],
  'gddkia': ['drogi', 'budowa', 'krajowe', 'autostrady'],
  'giełda': ['akcje', 'obligacje', 'gpw', 'inwestycje', 'makler'],
  'górnik': ['kopalnia', 'węgiel', 'emerytura', 'odprawy'],
  'habilitacja': ['profesor', 'uczelnia', 'nauka', 'tytuł'],
  'hazard': ['gry', 'zakłady', 'uzależnienie', 'automaty'],
  'hodowla': ['zwierzęta', 'mleko', 'mięso', 'dobrostan'],
  'hospicjum': ['opieka', 'choroba', 'śmierć', 'paliatywna'],
  'immunitet': ['poseł', 'ochrona', 'uchylenie', 'prokuratura'],
  'in vitro': ['zapłodnienie', 'niepłodność', 'refundacja', 'etyka'],
  'interpelacja': ['poseł', 'minister', 'odpowiedź', 'pytanie'],
  'komornik': ['egzekucja', 'długi', 'windykacja', 'sąd', 'dłużnik'],
  'koncesja': ['nadawca', 'radio', 'telewizja', 'krrit'],
  'konsultacje': ['społeczne', 'mieszkańcy', 'opinia', 'inwestycja'],
  'kopalnia': ['węgiel', 'górnik', 'likwidacja', 'restrukturyzacja'],
  'kopciuch': ['ogrzewanie', 'wymiana', 'dotacja', 'smog'],
  'kosiniakowe': ['dziecko', 'rodzic', 'świadczenie', 'zasiłek'],
  'kowr': ['ziemia', 'rolnictwo', 'grunty', 'dzierżawa'],
  'krrit': ['media', 'koncesja', 'nadzór', 'abonament'],
  'krs': ['sędziowie', 'nominacje', 'sąd', 'reforma'],
  'krus': ['rolnik', 'ubezpieczenie', 'emerytura', 'składka'],
  'kuratela': ['opieka', 'sąd', 'nieletni', 'ubezwłasnowolnienie'],
  'kurator': ['oświata', 'szkoła', 'nadzór', 'województwo'],
  'liceum': ['szkoła', 'matura', 'uczeń', 'edukacja'],
  'lotnisko': ['samolot', 'transport', 'pas', 'terminal'],
  'mObywatel': ['aplikacja', 'dokumenty', 'cyfryzacja', 'telefon'],
  'mandat': ['poseł', 'wybory', 'kadencja', 'immunitet'],
  'marihuana': ['legalizacja', 'medyczna', 'narkotyki', 'prawo'],
  'marszałek': ['województwo', 'sejmik', 'zarząd', 'region'],
  'metro': ['transport', 'miejski', 'linia', 'stacja'],
  'minimalna': ['płaca', 'wynagrodzenie', 'praca', 'pracodawca'],
  'mobilizacja': ['wojsko', 'rezerwa', 'obronność', 'kryzys'],
  'muzeum': ['kultura', 'wystawa', 'zbiory', 'dziedzictwo'],
  'nadgodziny': ['praca', 'wynagrodzenie', 'kodeks pracy', 'pracodawca'],
  'nato': ['sojusz', 'obronność', 'art5', 'wojsko'],
  'niepełnosprawność': ['orzeczenie', 'renta', 'rehabilitacja', 'pomoc'],
  'notariusz': ['akt', 'umowa', 'poświadczenie', 'testament'],
  'obligacje': ['dług', 'emisja', 'skarb państwa', 'oprocentowanie'],
  'onkologia': ['rak', 'leczenie', 'szpital', 'chemioterapia'],
  'opieka': ['dziecko', 'senior', 'choroba', 'pomoc'],
  'opiekun': ['niepełnosprawność', 'świadczenie', 'zasiłek', 'opieka'],
  'oze': ['odnawialna', 'energia', 'wiatrak', 'fotowoltaika', 'biomasa'],
  'piecza': ['zastępcza', 'dziecko', 'rodzina', 'opieka'],
  'pielęgniarka': ['szpital', 'opieka', 'zdrowie', 'wynagrodzenie'],
  'pkp': ['kolej', 'pociąg', 'bilet', 'spółka'],
  'plony': ['uprawy', 'rolnictwo', 'zbiory', 'ceny'],
  'podstawówka': ['szkoła', 'uczeń', 'edukacja', 'reforma'],
  'prokurator': ['oskarżenie', 'śledztwo', 'sąd', 'przestępstwo'],
  'prosument': ['energia', 'prąd', 'fotowoltaika', 'sieć'],
  'przedszkole': ['dziecko', 'edukacja', 'opieka', 'gmina'],
  'przysposobienie': ['adopcja', 'dziecko', 'rodzina', 'sąd'],
  'psychiatria': ['zdrowie', 'psychika', 'leczenie', 'terapia'],
  'radca': ['prawny', 'prawnik', 'pełnomocnik', 'zastępstwo'],
  'radio': ['publiczne', 'nadawca', 'abonament', 'koncesja'],
  'ratownik': ['pogotowie', 'medyczny', 'karetka', 'wypadek'],
  'recepta': ['lek', 'lekarz', 'apteka', 'refundacja'],
  'recykling': ['odpady', 'segregacja', 'opakowania', 'środowisko'],
  'referendum': ['głosowanie', 'obywatele', 'decyzja', 'lokalne'],
  'refundacja': ['lek', 'apteka', 'nfz', 'cena', 'leczenie'],
  'regulamin': ['sejm', 'obrady', 'procedura', 'głosowanie'],
  'rehabilitacja': ['zdrowie', 'niepełnosprawność', 'terapia', 'sanatorium'],
  'rencista': ['niepełnosprawność', 'zus', 'świadczenie', 'orzeczenie'],
  'rodo': ['dane', 'osobowe', 'ochrona', 'prywatność'],
  'rok': ['oskarżenie', 'śledztwo', 'sąd', 'przestępstwo'],
  'sanatorium': ['rehabilitacja', 'leczenie', 'zus', 'zdrowie'],
  'sejm': ['posłowie', 'głosowanie', 'ustawa', 'komisja'],
  'sejmowych': ['posłowie', 'głosowanie', 'ustawa', 'komisja'],
  'senat': ['senatorowie', 'poprawki', 'ustawa', 'izba'],
  'smog': ['powietrze', 'zanieczyszczenie', 'normy', 'kopciuch'],
  'spadek': ['dziedziczenie', 'testament', 'majątek', 'rodzina'],
  'spraw': ['orzeczenie', 'renta', 'rehabilitacja', 'pomoc'],
  'starosta': ['powiat', 'administracja', 'urząd', 'wybory'],
  'strajk': ['protest', 'pracownicy', 'związek', 'płaca'],
  'straż': ['pożarna', 'graniczna', 'miejska', 'gminna'],
  'stypendium': ['student', 'nauka', 'uczelnia', 'pomoc', 'dochód'],
  'subwencja': ['dotacja', 'finanse', 'samorząd', 'oświata', 'gmina'],
  'susza': ['rolnictwo', 'klęska', 'odszkodowanie', 'plony'],
  'szczepienia': ['obowiązek', 'covid', 'dziecko', 'kalendarz'],
  'szczepionka': ['covid', 'epidemia', 'zdrowie', 'profilaktyka', 'obowiązek'],
  'szpital': ['leczenie', 'pacjent', 'lekarz', 'zdrowie', 'nfz'],
  'sztuczna inteligencja': ['ai', 'algorytmy', 'regulacje', 'etyka'],
  'sędzia': ['sąd', 'wyrok', 'niezawisłość', 'nominacja'],
  'służby': ['specjalne', 'abw', 'cba', 'wywiad', 'bezpieczeństwo'],
  'tabor': ['transport', 'pojazdy', 'wymiana', 'zakup'],
  'teatr': ['kultura', 'sztuka', 'dotacja', 'artysty'],
  'technikum': ['szkoła', 'zawód', 'kwalifikacje', 'praktyka'],
  'testament': ['spadek', 'dziedziczenie', 'notariusz', 'majątek'],
  'tramwaj': ['transport', 'miejski', 'komunikacja', 'tabor'],
  'trybunał': ['konstytucyjny', 'stanu', 'sąd', 'wyrok'],
  'trzynastka': ['emerytura', 'świadczenie', 'bonus', 'zus'],
  'tvp': ['telewizja', 'publiczna', 'abonament', 'zarząd'],
  'upadłość': ['bankructwo', 'niewypłacalność', 'firma', 'restrukturyzacja'],
  'urlop': ['wypoczynek', 'pracownik', 'macierzyński', 'ojcowski'],
  'waloryzacja': ['podwyżka', 'emerytura', 'renta', 'płaca', 'inflacja'],
  'weto': ['prezydent', 'ustawa', 'odrzucenie', 'podpis'],
  'wiatrak': ['energia', 'wiatr', 'farma', 'oze'],
  'więzienie': ['kara', 'skazany', 'areszt', 'resocjalizacja'],
  'wojewoda': ['rząd', 'nadzór', 'administracja', 'przedstawiciel'],
  'wot': ['obrona', 'terytorialna', 'wojsko', 'ochotnicy'],
  'wotum': ['nieufności', 'zaufania', 'rząd', 'premier'],
  'wójt': ['gmina', 'wybory', 'samorząd', 'wieś'],
  'węgiel': ['kopalnia', 'górnik', 'emisja', 'energia'],
  'zabytek': ['ochrona', 'konserwator', 'remont', 'dotacja'],
  'zapytanie': ['poseł', 'minister', 'odpowiedź', 'kontrola'],
  'związek': ['zawodowy', 'pracownicy', 'strajk', 'negocjacje'],
  'zwolnienie': ['praca', 'lekarskie', 'chorobowe', 'pracodawca'],
  'ławnik': ['sąd', 'społeczny', 'orzeczenie', 'kadencja'],
  'śledztwo': ['prokuratura', 'policja', 'przestępstwo', 'dowody'],
  'żandarmeria': ['wojsko', 'policja', 'wojskowa', 'żołnierz'],
  'żłobek': ['dziecko', 'opieka', 'rodzic', 'praca'],
};